name: deploy tf plan contains encrypted file

on: 
  workflow_dispatch 

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: echo some env vars
          run: | 
           ls
           git init
           git config --global user.name "$GITHUB_ACTOR"
           git config --global user.email "$GITHUB_ACTOR@gmail.com"
           git remote -v
           git status 
