name: deploy tf plan contains encrypted file

on: 
  workflow_dispatch 

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: push to rep 
          run: | 
           ls
           chmod +x run.sh
           ./run.sh
           git remote -v
           git add -A
           git commit -m "first commit"
           git push origin main
