name: deploy tf plan contains encrypted file

on: 
  workflow_dispatch 

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: push to rep 
          run: | 
           ls
           git remote -v
           git status 
