name: deploy tf plan contains encrypted file

on: 
  workflow_dispatch 

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: echo some env vars
          run: |
           echo $GITHUB_ACTOR
           echo $GITHUB_TOKEN
        - name: git pull 
          run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
            git pull origin main

        - name: git push
          run: |
            ls -a
            echo $RANDOM >> random.txt
            git remote -v
            git add -A
            git commit -m "gh commit"
            git push origin main
